prom-conf:
    tty: true
    image: infinityworks/prom-conf:19
    volumes:
      - /etc/prom-conf/
    net: none

prometheus:
    tty: true
    image: prom/prometheus:v1.6.0
    command: -alertmanager.url=http://alertmanager:9093 -config.file=/etc/prom-conf/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
    ports:
      - 9090:9090
    labels:
      io.rancher.sidekicks: prom-conf
    volumes_from:
      - prom-conf
    volumes:
      - /data/
    external_links:
    - exporters/cadvisor:cadvisor
    - exporters/node-exporter:node-exporter
    - exporters/prometheus-rancher-exporter:prometheus-rancher-exporter
    extra_hosts:
    - "rancher-server:${RANCHER_SERVER}"

graf-db:
    tty: true
    image: infinityworks/graf-db:11
    command: cat
    volumes:
      - /var/lib/grafana/
    net: none

grafana:
    tty: true
    image: grafana/grafana:4.2.0
    ports:
      - 3000:3000
    labels:
      io.rancher.sidekicks: graf-db
    volumes_from:
       - graf-db
    external_links:
      - prometheus:prometheus
      - exporters/prometheus-rancher-exporter:prometheus-rancher-exporter

