name: Monitoring Primary
description: |
  Monitoring Primary
version: 1.0.0
category: Monitoring
maintainer: Jonathan Kosgei
license: MIT
projectURL: https://github.com/jonathan-kosgei/rancher-cattle-monitoring
