name: Primary Monitoring
description: |
   Primary Monitoring
version: 1
category: Monitoring
maintainer: Jonathan Kosgei
license: MIT
projectURL: https://github.com/jonathan-kosgei/rancher-cattle-monitoring@primary
