ranch-eye:
  ports:
  - 9104:9104/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.dns: true
  tty: true
  image: rucknar/ranch-eye:01
  stdin_open: true
  net: "host"

node-exporter:
  ports:
    - 9100:9100
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.dns: true
  tty: true
  image: prom/node-exporter:latest
  stdin_open: true
  net: "host"

  rancher-api-integration:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    expose:
      - 9010:9010
    image: rucknar/prometheus-rancher-exporter:01