prom-conf:
    tty: true
    image: rucknar/prom-conf:08
    volumes:
      - /etc/prom-conf/

prometheus:
    tty: true
    image: prom/prometheus:0.17.0
    command: -alertmanager.url=http://alertmanager:9093 -config.file=/etc/prom-conf/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles
    ports:
      - 9090:9090
    labels:
      io.rancher.sidekicks: prom-conf
    volumes_from:
       - prom-conf
    external_links:
      - exporters/ranch-eye:ranch-eye
      - exporters/node-exporter:node-exporter
      - exporters/rancher-api-integration:rancher-api-integration

influxdb:
  image: tutum/influxdb:0.10
  ports:
    - 8083:8083
    - 8086:8086
    - 8090:8090
    - 2003:2003
  environment:
    - PRE_CREATE_DB=grafana;prometheus;rancher
    - GRAPHITE_DB=rancher
    - GRAPHITE_BINDING=:2003

graf-db:
    tty: true
    image: rucknar/graf-db:02
    command: cat
    volumes:
      - /var/lib/grafana/

grafana:
    tty: true
    image: grafana/grafana:2.6.0
    ports:
      - 3000:3000
    labels:
      io.rancher.sidekicks: graf-db
    volumes_from:
       - graf-db
    links:
      - prometheus:prometheus
      - exporters/rancher-api-integration:rancher-api-integration