.catalog:
  name: Primary Monitoring
  version: 1
  description: Primary Monitoring
  uuid: primary-monitoring
  minimum_rancher_version: v0.56.0
  questions:

prometheus:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

influxdb:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 8086
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

grafana:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000