.catalog:
  name: Exporters Monitoring
  version: 1
  description: Exporters Monitoring
  uuid: exporters-monitoring
  minimum_rancher_version: v0.56.0
  questions:

ranch-eye:
  upgrade_strategy:
    start_first: true

node-exporter:
  upgrade_strategy:
    start_first: true

rancher-api-integration:
  upgrade_strategy:
    start_first: true
  scale: 1
  health_check:
    port: 9010
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000